// Generated by CoffeeScript 1.3.3
(function() {
  var compilers, files, utils;

  files = require('./files');

  utils = require('./utils');

  compilers = module.exports = {
    jade: {
      compilesTo: 'html',
      compile: function(str, options, cb) {
        this.jade || (this.jade = require("jade"));
        str = this.jade.compile(str, options)(options);
        return cb(null, str);
      }
    },
    md: {
      compilesTo: 'html',
      compile: function(str, options, cb) {
        this.markdown || (this.markdown = require("markdown").markdown);
        str = this.markdown.toHTML(str);
        return cb(null, str);
      }
    },
    styl: {
      compilesTo: 'css',
      compile: function(str, options, cb) {
        this.stylus || (this.stylus = require("stylus"));
        return this.stylus.render(str, options, cb);
      }
    },
    less: {
      compilesTo: 'css',
      compile: function(str, options, cb) {
        this.less || (this.less = require("less"));
        return this.less.render(str, options, cb);
      }
    },
    coffee: {
      compilesTo: 'js',
      compile: function(str, options, cb) {
        this.coffee || (this.coffee = require("coffee-script"));
        return cb(null, this.coffee.compile(str, options));
      }
    },
    "default": {
      encoding: null,
      compile: function(str, options, cb) {
        return cb(null, str);
      }
    },
    forFile: function(file) {
      var compiler, ext;
      ext = utils.extname(file);
      compiler = compilers[ext] || compilers["default"];
      return compiler;
    }
  };

}).call(this);
