// Generated by CoffeeScript 1.3.3
(function() {
  var FileRegistry, compilers, exports, fs, pathUtils, utils, worker;

  fs = require('fs');

  pathUtils = require('path');

  compilers = require('./compilers');

  utils = require('./utils');

  worker = require('./worker');

  FileRegistry = (function() {

    function FileRegistry(source, target) {
      this.source = source;
      this.target = target;
      this.dependencies = {};
      this.workers = new worker.WorkerQueue();
    }

    FileRegistry.prototype.addFile = function(path, stats, cb) {
      var compiler, job, sourcePath, targetPath,
        _this = this;
      compiler = compilers.forFile(path);
      sourcePath = pathUtils.join(this.source, path);
      if (compiler.compilesTo) {
        path = utils.newext(path, compiler.compilesTo);
      }
      targetPath = pathUtils.join(this.target, path);
      job = {
        source: sourcePath,
        target: targetPath,
        options: {
          filename: sourcePath
        }
      };
      utils.log("info", "Building " + path);
      return this.workers.queueJob("compile", job, function(e, result) {
        if (!e) {
          _this.dependencies[path] = result.dependencies;
        }
        return cb(e);
      });
    };

    FileRegistry.prototype.scan = function(cb) {
      return utils.iterateFolder(this.source, exports.ignore, this.addFile.bind(this), cb);
    };

    return FileRegistry;

  })();

  exports = module.exports = FileRegistry;

  exports.ignore = ['node_modules', '_build'];

}).call(this);
