// Generated by CoffeeScript 1.3.3
(function() {
  var FileRegistry, Server, pathUtils, utils;

  pathUtils = require('path');

  utils = require('./utils');

  FileRegistry = require('./fileregistry');

  Server = require('./server');

  exports.version = "0.3.0";

  exports.start = function(options) {
    var registry, server;
    registry = new FileRegistry();
    registry.scan(function() {
      return utils.log("info", "Finished scan");
    });
    return server = new Server(registry);
  };

}).call(this);
