// Generated by CoffeeScript 1.3.3
(function() {
  var Server, express, pathUtils, url, utils,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  express = require('express');

  pathUtils = require('path');

  url = require('url');

  utils = require('./utils');

  Server = (function() {

    function Server(registry) {
      var accessibleAt, app, server;
      this.registry = registry;
      this.checkRegistry = __bind(this.checkRegistry, this);

      app = express.createServer();
      app.use(express.logger('dev'));
      app.use(express.favicon());
      app.use(express["static"](process.env.PRO_TARGET));
      app.use(express.directory(process.env.PRO_TARGET, {
        icons: true
      }));
      server = url.parse(process.env.PRO_BASE_URL);
      if (server.protocol === 'http:') {
        require('http').createServer(app).listen(server.port || 80, server.hostname);
      } else {
        require('https').createServer(app).listen(server.port || 443, server.hostname);
      }
      accessibleAt = server.protocol + "//localhost" + (server.port && (":" + server.port)) + "/";
      utils.log("info", "Prototyper server running on " + accessibleAt);
    }

    Server.prototype.checkRegistry = function(req, res, next) {
      var path;
      path = url.parse(req.url).pathname.slice(1);
      if (path[path.length - 1] === '/') {
        path += "index.html";
      }
      path = pathUtils.normalize(path);
      return this.registry.lookupTarget(path, function(err, file) {
        return next(err);
      });
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
