// Generated by CoffeeScript 1.3.3
(function() {
  var Minimatch, accessed, filter, filters, fs, fsLevel, h, hooked, ignored, patchFunction, _i, _j, _len, _len1,
    __slice = [].slice;

  fs = require('fs');

  Minimatch = require('minimatch').Minimatch;

  hooked = ["readFile", "readFileSync", "open", "openSync", "stat", "statSync", "exists", "existsSync", "createReadStream"];

  ignored = ["writeFile", "writeFileSync"];

  filters = exports.defaultFilters = [
    new Minimatch("!**/node_modules/**"), new Minimatch("**", {
      dot: false
    })
  ];

  patchFunction = function(name, ignore) {
    var old;
    if (ignore == null) {
      ignore = false;
    }
    old = fs[name];
    return fs[name] = function() {
      var args, f, filtered, path, result, _i, _len;
      path = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (fsLevel++ === 0 && !ignore) {
        filtered = false;
        for (_i = 0, _len = filters.length; _i < _len; _i++) {
          f = filters[_i];
          if (!f.match(path)) {
            filtered = true;
          }
        }
        if (!filtered) {
          accessed[path] = (accessed[path] || 0) + 1;
        }
      }
      try {
        return result = old.apply(null, [path].concat(__slice.call(args)));
      } finally {
        fsLevel--;
      }
    };
  };

  for (_i = 0, _len = hooked.length; _i < _len; _i++) {
    h = hooked[_i];
    patchFunction(h);
  }

  for (_j = 0, _len1 = ignored.length; _j < _len1; _j++) {
    h = ignored[_j];
    patchFunction(h, true);
  }

  accessed = {};

  fsLevel = 0;

  filter = null;

  exports.clear = function() {
    return accessed = {};
  };

  exports.setFilter = function(f) {
    return filters = exports.defaultFilters.concat(f && [new Minimatch(f)] || []);
  };

  exports.getAccessed = function() {
    return Object.keys(accessed);
  };

}).call(this);
