// Generated by CoffeeScript 1.3.3
(function() {
  var compilers, fs, monitor;

  fs = require('fs');

  monitor = require('./fs-monitor');

  compilers = require('../compilers');

  exports.compile = function(job, cb) {
    var compiler, encoding, file;
    compiler = compilers.forFile(job.source);
    encoding = 'encoding' in compiler ? compiler.encoding : 'utf8';
    monitor.clear();
    file = fs.readFileSync(job.source, encoding);
    try {
      return compiler.compile(file, job.options, function(err, result) {
        if (!err) {
          fs.writeFileSync(job.target, result, encoding);
        }
        return cb(err, {
          dependencies: monitor.getAccessed()
        });
      });
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
