// Generated by CoffeeScript 1.3.3
(function() {
  var currentJob;

  exports.jobs = require('./jobs');

  currentJob = null;

  exports.handleMessage = function(m) {
    if (currentJob) {
      throw new Error("Worker received a job while still processing another job. Something is broken.");
    }
    currentJob = exports.jobs[m.job];
    if (!currentJob) {
      console.log("Unknown job " + m.job);
      return;
    }
    return currentJob(m.data, function(err, result) {
      if (err) {
        process.send({
          status: "error",
          error: {
            stack: err.stack,
            message: err.message,
            name: err.name
          }
        });
      } else {
        process.send({
          status: "success",
          result: result
        });
      }
      return currentJob = null;
    });
  };

  process.on('message', exports.handleMessage);

}).call(this);
